[CmdletBinding()]
param(
    # One or more native-buff-catalog-audit.json files written by the guarded
    # native-buff-catalog scenario (one per compatibility profile).
    [Parameter(Mandatory = $true)][string[]]$AuditPath,
    # The human-readable Markdown report to write.
    [Parameter(Mandatory = $true)][string]$OutputPath
)

# The 0.4.0 catalogue audit (WP5): renders the machine-readable audit that the
# game wrote into a human-readable report. It reads nothing else and changes
# nothing but the output file.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Format-KbpCell([object]$Value) {
    $text = if ($null -eq $Value) { '' } else { [string]$Value }
    return ($text -replace '\|', '\|' -replace '\r?\n', ' ').Trim()
}

function Format-KbpEffects([object[]]$Effects) {
    return (@($Effects | ForEach-Object { "$($_.effectName) ($($_.effectGuid), $($_.target))" }) -join '; ')
}

$audits = @()
foreach ($path in $AuditPath) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Audit file is missing: $path" }
    $audit = Get-Content -LiteralPath $path -Raw | ConvertFrom-Json
    if ([int]$audit.schemaVersion -ne 1 -or [string]::IsNullOrWhiteSpace([string]$audit.profile)) {
        throw "Not a catalogue audit (schemaVersion 1): $path"
    }
    if ([int]$audit.summary.addedCount -ne 0) {
        throw "The audit of $($audit.profile) reports added entries; the 0.4.0 rules only remove: $path"
    }
    $hash = (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
    $audits += [pscustomobject]@{ Path = $path; Sha256 = $hash; Audit = $audit }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Beneficial-buff catalogue audit (0.4.0, WP5)')
$lines.Add('')
$lines.Add('Generated by `scripts/ConvertTo-KbpCatalogAuditReport.ps1` from the audit the game wrote')
$lines.Add('during the guarded `native-buff-catalog` scenario. "Before" is the catalogue under the rules')
$lines.Add('released through 0.3.0; "after" is the 0.4.0 rules, both computed in the same run from the')
$lines.Add('same facts. The static scope is what the exact player class/race/feat graph reaches; the live')
$lines.Add('scope classifies every ability as reachable, which is how live discovery judges the abilities')
$lines.Add('a party member actually has.')
$lines.Add('')
$lines.Add('| Profile | Generator commit | Audit file | SHA-256 |')
$lines.Add('| --- | --- | --- | --- |')
foreach ($entry in $audits) {
    $lines.Add("| $($entry.Audit.profile) | ``$($entry.Audit.generatorCommit)`` | ``$(Format-KbpCell $entry.Path)`` | ``$($entry.Sha256)`` |")
}
$lines.Add('')
$lines.Add('## Counts')
$lines.Add('')
$lines.Add('| Profile | Ownership | Static before | Static after | Live before | Live after |')
$lines.Add('| --- | --- | ---: | ---: | ---: | ---: |')
foreach ($entry in $audits) {
    $totals = $entry.Audit.summary.totals
    $lines.Add("| $($entry.Audit.profile) | **all** | $($totals.staticIncludedBefore040) | $($totals.staticIncluded) | $($totals.liveIncludedBefore040) | $($totals.liveIncluded) |")
    foreach ($property in @($entry.Audit.summary.byOwnership.PSObject.Properties | Sort-Object Name)) {
        $counts = $property.Value
        $lines.Add("| $($entry.Audit.profile) | $($property.Name) | $($counts.staticIncludedBefore040) | $($counts.staticIncluded) | $($counts.liveIncludedBefore040) | $($counts.liveIncluded) |")
    }
}
$lines.Add('')
$lines.Add('## Removed by rule')
$lines.Add('')
$lines.Add('| Profile | Reason | Removed |')
$lines.Add('| --- | --- | ---: |')
foreach ($entry in $audits) {
    foreach ($property in @($entry.Audit.summary.removedByReason.PSObject.Properties | Sort-Object Name)) {
        $lines.Add("| $($entry.Audit.profile) | $($property.Name) | $($property.Value) |")
    }
}
foreach ($entry in $audits) {
    $records = @($entry.Audit.records)
    $removed = @($records | Where-Object { $_.status -ceq 'removed-by-0.4.0-audit' })
    $included = @($records | Where-Object { $_.status -ceq 'included' })
    $lines.Add('')
    $lines.Add("## $($entry.Audit.profile): removed ($($removed.Count))")
    $lines.Add('')
    $lines.Add('| Name | Blueprint | Ownership | Source kind | Scope | Exclusion reason |')
    $lines.Add('| --- | --- | --- | --- | --- | --- |')
    foreach ($record in $removed) {
        $lines.Add("| $(Format-KbpCell $record.displayName) | ``$($record.abilityGuid)`` ($(Format-KbpCell $record.internalName)) | $($record.ownership) | $($record.sourceKind) | $($record.scope) | $(Format-KbpCell $record.exclusionReason) |")
    }
    $lines.Add('')
    $lines.Add("## $($entry.Audit.profile): included ($($included.Count))")
    $lines.Add('')
    $lines.Add('| Name | Blueprint | Ownership | Source kind | Scope | Provider | Rule | Persistent beneficial effect | Targets | Execution | Qualification |')
    $lines.Add('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |')
    foreach ($record in $included) {
        $rule = if ([string]::IsNullOrEmpty([string]$record.manualOverride)) { $record.inclusionRule } else { "override: $($record.manualOverride)" }
        $lines.Add("| $(Format-KbpCell $record.displayName) | ``$($record.abilityGuid)`` | $($record.ownership) | $($record.sourceKind) | $($record.scope) | $(Format-KbpCell $record.provider) | $(Format-KbpCell $rule) | $(Format-KbpCell (Format-KbpEffects @($record.persistentBeneficialEffects))) | $($record.targetSemantics) | $($record.executionSupport) | $($record.qualificationStatus) |")
    }
}

$directory = Split-Path -Parent ([IO.Path]::GetFullPath($OutputPath))
if (-not (Test-Path -LiteralPath $directory -PathType Container)) { throw "Output directory is missing: $directory" }
[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath), (($lines -join "`n") + "`n"),
    [Text.UTF8Encoding]::new($false))
"Wrote $OutputPath from $($audits.Count) audit file(s)."
